import { cva } from "class-variance-authority"

export const typographyVariants = cva("", {
  variants: {
    variant: {
      "display-lg": [
        "[font-family:var(--tfds-font-family-display)]",
        "[font-size:var(--tfds-font-size-5xl)]",
        "[font-weight:var(--tfds-font-weight-bold)]",
        "[line-height:var(--tfds-font-line-height-tight)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-tight)]",
      ],
      "display-md": [
        "[font-family:var(--tfds-font-family-display)]",
        "[font-size:var(--tfds-font-size-4xl)]",
        "[font-weight:var(--tfds-font-weight-bold)]",
        "[line-height:var(--tfds-font-line-height-tight)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-tight)]",
      ],
      "display-sm": [
        "[font-family:var(--tfds-font-family-display)]",
        "[font-size:var(--tfds-font-size-3xl)]",
        "[font-weight:var(--tfds-font-weight-semibold)]",
        "[line-height:var(--tfds-font-line-height-snug)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-tight)]",
      ],
      "heading-xl": [
        "[font-family:var(--tfds-font-family-display)]",
        "[font-size:var(--tfds-font-size-2xl)]",
        "[font-weight:var(--tfds-font-weight-semibold)]",
        "[line-height:var(--tfds-font-line-height-snug)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-normal)]",
      ],
      "heading-lg": [
        "[font-family:var(--tfds-font-family-sans)]",
        "[font-size:var(--tfds-font-size-xl)]",
        "[font-weight:var(--tfds-font-weight-semibold)]",
        "[line-height:var(--tfds-font-line-height-snug)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-normal)]",
      ],
      "heading-md": [
        "[font-family:var(--tfds-font-family-sans)]",
        "[font-size:var(--tfds-font-size-lg)]",
        "[font-weight:var(--tfds-font-weight-semibold)]",
        "[line-height:var(--tfds-font-line-height-snug)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-normal)]",
      ],
      "heading-sm": [
        "[font-family:var(--tfds-font-family-sans)]",
        "[font-size:var(--tfds-font-size-md)]",
        "[font-weight:var(--tfds-font-weight-semibold)]",
        "[line-height:var(--tfds-font-line-height-normal)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-normal)]",
      ],
      "body-lg": [
        "[font-family:var(--tfds-font-family-sans)]",
        "[font-size:var(--tfds-font-size-lg)]",
        "[font-weight:var(--tfds-font-weight-regular)]",
        "[line-height:var(--tfds-font-line-height-relaxed)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-normal)]",
      ],
      "body-md": [
        "[font-family:var(--tfds-font-family-sans)]",
        "[font-size:var(--tfds-font-size-md)]",
        "[font-weight:var(--tfds-font-weight-regular)]",
        "[line-height:var(--tfds-font-line-height-relaxed)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-normal)]",
      ],
      "body-sm": [
        "[font-family:var(--tfds-font-family-sans)]",
        "[font-size:var(--tfds-font-size-sm)]",
        "[font-weight:var(--tfds-font-weight-regular)]",
        "[line-height:var(--tfds-font-line-height-normal)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-normal)]",
      ],
      "label-lg": [
        "[font-family:var(--tfds-font-family-sans)]",
        "[font-size:var(--tfds-font-size-md)]",
        "[font-weight:var(--tfds-font-weight-medium)]",
        "[line-height:var(--tfds-font-line-height-normal)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-wide)]",
      ],
      "label-md": [
        "[font-family:var(--tfds-font-family-sans)]",
        "[font-size:var(--tfds-font-size-sm)]",
        "[font-weight:var(--tfds-font-weight-medium)]",
        "[line-height:var(--tfds-font-line-height-normal)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-wide)]",
      ],
      "label-sm": [
        "[font-family:var(--tfds-font-family-sans)]",
        "[font-size:var(--tfds-font-size-xs)]",
        "[font-weight:var(--tfds-font-weight-medium)]",
        "[line-height:var(--tfds-font-line-height-normal)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-wide)]",
      ],
      caption: [
        "[font-family:var(--tfds-font-family-sans)]",
        "[font-size:var(--tfds-font-size-xs)]",
        "[font-weight:var(--tfds-font-weight-regular)]",
        "[line-height:var(--tfds-font-line-height-normal)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-normal)]",
      ],
      code: [
        "[font-family:var(--tfds-font-family-mono)]",
        "[font-size:var(--tfds-font-size-sm)]",
        "[font-weight:var(--tfds-font-weight-regular)]",
        "[line-height:var(--tfds-font-line-height-normal)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-normal)]",
      ],
      overline: [
        "[font-family:var(--tfds-font-family-sans)]",
        "[font-size:var(--tfds-font-size-xs)]",
        "[font-weight:var(--tfds-font-weight-semibold)]",
        "[line-height:var(--tfds-font-line-height-normal)]",
        "[letter-spacing:var(--tfds-font-letter-spacing-wide)]",
        "uppercase",
      ],
    },
    color: {
      primary: "[color:var(--tfds-color-text-primary)]",
      secondary: "[color:var(--tfds-color-text-secondary)]",
      disabled: "[color:var(--tfds-color-text-disabled)]",
      onBrand: "[color:var(--tfds-color-text-on-brand)]",
      error: "[color:var(--tfds-color-text-error)]",
      success: "[color:var(--tfds-color-text-success)]",
      warning: "[color:var(--tfds-color-text-warning)]",
    },
    align: {
      left: "text-left",
      center: "text-center",
      right: "text-right",
      justify: "text-justify",
    },
    truncate: {
      true: "truncate",
      false: "",
    },
  },
  defaultVariants: {
    variant: "body-md",
    color: "primary",
    align: "left",
    truncate: false,
  },
})
