import StyleDictionary from "style-dictionary"

const themes = [
  { name: "light", selector: ":root" },
  { name: "dark", selector: ".dark" },
  { name: "ocean-sunset", selector: ".ocean-sunset" },
]

const primitiveFiles = [
  "src/primitive/color.tokens.json",
  "src/primitive/typography.tokens.json",
  "src/primitive/spacing.tokens.json",
  "src/primitive/effect.tokens.json",
]

function collectTokenNodes(tree, prefix = []) {
  const nodes = new Map()

  for (const [key, value] of Object.entries(tree)) {
    const path = [...prefix, key]

    if (value === null || typeof value !== "object" || Array.isArray(value)) {
      continue
    }

    if ("$value" in value) {
      nodes.set(path.join("."), value)
    } else {
      for (const [nestedPath, node] of collectTokenNodes(value, path)) {
        nodes.set(nestedPath, node)
      }
    }
  }

  return nodes
}

async function loadTokenFile(path) {
  const { readFile } = await import("fs/promises")
  const raw = await readFile(path, "utf-8")

  try {
    return JSON.parse(raw)
  } catch (err) {
    throw new Error(`Invalid JSON in ${path}: ${err.message}`)
  }
}

const ALIAS_PATTERN = /^\{([^}]+)\}$/

async function validateTokenFiles(files = [...primitiveFiles, ...themes.map((t) => `src/semantic/${t.name}.tokens.json`)]) {
  const fileTrees = []
  const allNodes = new Map()

  for (const file of files) {
    const tree = await loadTokenFile(file)
    const nodes = collectTokenNodes(tree)
    fileTrees.push({ file, nodes })

    for (const [path, node] of nodes) {
      if (!("$type" in node)) {
        throw new Error(`Invalid DTCG token in ${file}: "${path}" has $value but is missing $type`)
      }
      allNodes.set(path, node)
    }
  }

  for (const { file, nodes } of fileTrees) {
    for (const [path, node] of nodes) {
      if (typeof node.$value !== "string") continue

      const match = node.$value.match(ALIAS_PATTERN)
      if (!match) continue

      const refPath = match[1]
      if (!allNodes.has(refPath)) {
        throw new Error(`Broken alias in ${file}: token "${path}" references "{${refPath}}", which does not exist`)
      }
    }
  }
}

async function buildPrimitives() {
  const sd = new StyleDictionary({
    usesDtcg: true,
    source: primitiveFiles,
    platforms: {
      css: {
        transformGroup: "css",
        prefix: "tfds",
        buildPath: "dist/css/",
        files: [
          {
            destination: "primitives.css",
            format: "css/variables",
            options: { selector: ":root", outputReferences: false },
          },
        ],
      },
      js: {
        transformGroup: "js",
        buildPath: "dist/js/",
        files: [
          {
            destination: "primitives.js",
            format: "javascript/es6",
          },
        ],
      },
    },
  })

  await sd.buildAllPlatforms()
}

async function buildTheme(theme) {
  const sd = new StyleDictionary({
    usesDtcg: true,
    source: [`src/semantic/${theme.name}.tokens.json`],
    platforms: {
      css: {
        transformGroup: "css",
        prefix: "tfds",
        buildPath: "dist/css/themes/",
        files: [
          {
            destination: `${theme.name}.css`,
            format: "css/variables",
            options: { selector: theme.selector, outputReferences: false },
          },
        ],
      },
      js: {
        transformGroup: "js",
        buildPath: "dist/js/themes/",
        files: [
          {
            destination: `${theme.name}.js`,
            format: "javascript/es6",
          },
        ],
      },
    },
  })

  await sd.buildAllPlatforms()
}

async function buildThemeJson(theme) {
  const sd = new StyleDictionary({
    usesDtcg: true,
    source: [...primitiveFiles, `src/semantic/${theme.name}.tokens.json`],
    platforms: {
      json: {
        transformGroup: "js",
        buildPath: "dist/json/",
        files: [
          {
            destination: `${theme.name}.json`,
            format: "json/nested",
            options: { outputReferences: false },
          },
        ],
      },
    },
  })

  await sd.buildAllPlatforms()
}

function flattenTokenNames(tree, prefix = []) {
  const names = []

  for (const [key, value] of Object.entries(tree)) {
    const path = [...prefix, key]

    if (value !== null && typeof value === "object" && !Array.isArray(value)) {
      names.push(...flattenTokenNames(value, path))
    } else {
      names.push(path.join("."))
    }
  }

  return names
}

async function buildTypes() {
  const { readFile, writeFile, mkdir } = await import("fs/promises")

  const referenceTheme = themes[0]
  const raw = await readFile(`dist/json/${referenceTheme.name}.json`, "utf-8")
  const tree = JSON.parse(raw)
  const names = flattenTokenNames(tree).sort()

  const union = names.map((name) => `  | "${name}"`).join("\n")
  const content = `// Generated by build.js — do not edit by hand.\nexport type TokenName =\n${union}\n`

  await mkdir("dist/types", { recursive: true })
  await writeFile("dist/types/token-names.d.ts", content)
}

async function buildIndex() {
  const cssImports = [
    `@import './primitives.css';`,
    ...themes.map((t) => `@import './themes/${t.name}.css';`),
  ].join("\n")

  const { writeFile, mkdir } = await import("fs/promises")
  await mkdir("dist/css", { recursive: true })
  await writeFile("dist/css/index.css", cssImports)
}

async function buildTailwindPreset() {
  const preset = `
export default {
  theme: {
    extend: {
      colors: {
        "text-primary":          "var(--tfds-color-text-primary)",
        "text-secondary":        "var(--tfds-color-text-secondary)",
        "text-tertiary":         "var(--tfds-color-text-tertiary)",
        "text-disabled":         "var(--tfds-color-text-disabled)",
        "text-inverse":          "var(--tfds-color-text-inverse)",
        "text-on-brand":         "var(--tfds-color-text-on-brand)",
        "bg-page":               "var(--tfds-color-bg-page)",
        "bg-default":            "var(--tfds-color-bg-default)",
        "bg-subtle":             "var(--tfds-color-bg-subtle)",
        "bg-muted":              "var(--tfds-color-bg-muted)",
        "surface-default":       "var(--tfds-color-surface-default)",
        "surface-raised":        "var(--tfds-color-surface-raised)",
        "surface-sunken":        "var(--tfds-color-surface-sunken)",
        "border-default":        "var(--tfds-color-border-default)",
        "border-subtle":         "var(--tfds-color-border-subtle)",
        "border-strong":         "var(--tfds-color-border-strong)",
        "action-primary":        "var(--tfds-color-action-primary)",
        "action-primary-hover":  "var(--tfds-color-action-primary-hover)",
        "feedback-success":      "var(--tfds-color-feedback-success)",
        "feedback-error":        "var(--tfds-color-feedback-error)",
        "feedback-warning":      "var(--tfds-color-feedback-warning)",
        "interactive-focus":     "var(--tfds-color-interactive-focus)",
      },
      fontFamily: {
        sans:    "var(--tfds-font-family-sans)",
        display: "var(--tfds-font-family-display)",
        mono:    "var(--tfds-font-family-mono)",
      },
      borderRadius: {
        none: "var(--tfds-radius-none)",
        xs:   "var(--tfds-radius-xs)",
        sm:   "var(--tfds-radius-sm)",
        md:   "var(--tfds-radius-md)",
        lg:   "var(--tfds-radius-lg)",
        xl:   "var(--tfds-radius-xl)",
        full: "var(--tfds-radius-full)",
      },
    },
  },
}
`.trim()

  const { writeFile, mkdir } = await import("fs/promises")
  await mkdir("dist/tailwind", { recursive: true })
  await writeFile("dist/tailwind/preset.js", preset)
}

async function cleanDist() {
  const { rm } = await import("fs/promises")
  await rm("dist", { recursive: true, force: true })
}

async function main() {
  console.log("Building @tfds/tokens...")

  await validateTokenFiles()
  await cleanDist()
  await buildPrimitives()
  for (const theme of themes) {
    await buildTheme(theme)
    await buildThemeJson(theme)
  }
  await buildTypes()
  await buildIndex()
  await buildTailwindPreset()

  console.log("Done!")
}

const isMain = process.argv[1] && import.meta.url === `file://${process.argv[1]}`

if (isMain) {
  main().catch((err) => {
    console.error(err)
    process.exit(1)
  })
}

export { main, themes, primitiveFiles, buildThemeJson, flattenTokenNames, validateTokenFiles }
